[2025-05-05 14:43:12,214: INFO: main: Welcome to the CNN Classifier]
[2025-05-05 14:43:20,644: INFO: main: Welcome to the CNN Classifier]
[2025-05-05 15:47:04,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 15:47:04,709: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 15:47:04,710: INFO: common: created directory at: artifacts]
[2025-05-05 15:47:04,712: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 15:47:04,713: INFO: 2187018522: Downloading data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 15:47:12,035: INFO: 2187018522: Downloaded data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 15:49:21,443: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 15:49:21,444: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 15:49:21,445: INFO: common: created directory at: artifacts]
[2025-05-05 15:49:21,446: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 15:49:21,447: INFO: 329266585: Downloading data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 15:49:29,255: INFO: 329266585: Downloaded data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 16:00:17,942: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-05 16:00:17,944: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 16:00:17,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 16:00:17,945: INFO: common: created directory at: artifacts]
[2025-05-05 16:00:17,945: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 16:00:17,946: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 16:00:24,742: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 16:00:24,987: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-05 21:30:13,040: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 21:30:13,043: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 21:30:13,045: INFO: common: created directory at: artifacts]
[2025-05-05 21:30:13,046: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 21:30:58,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 21:30:58,747: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 21:30:58,748: INFO: common: created directory at: artifacts]
[2025-05-05 21:30:58,749: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 21:31:04,962: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 21:31:39,163: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 21:31:39,165: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 21:31:39,167: INFO: common: created directory at: artifacts]
[2025-05-05 21:31:39,168: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 21:31:39,353: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 21:31:39,456: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 21:49:28,735: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-05 21:49:28,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 21:49:28,738: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 21:49:28,738: INFO: common: created directory at: artifacts]
[2025-05-05 21:49:28,738: ERROR: main: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config']
Traceback (most recent call last):
  File "C:\Users\aldoe\Documents\Projects_Python\CT-SCAN\main.py", line 10, in <module>
    obj.main()
  File "c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 20, in main
    raise e
  File "c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion_config = config.get_data_ingestion_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_data_ingestion_config'
[2025-05-05 21:51:42,101: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-05 21:51:42,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 21:51:42,102: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 21:51:42,104: INFO: common: created directory at: artifacts]
[2025-05-05 21:51:42,104: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-05 21:51:42,104: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 21:51:48,177: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1rUPO5fl7EeoE_oSRH--tiLY9fn-1Niso/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-05 21:51:48,366: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-05 21:51:48,366: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-05-05 21:51:48,367: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-05 21:51:48,368: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-05 21:51:48,369: INFO: common: created directory at: artifacts]
[2025-05-05 21:51:48,369: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-05 21:51:48,624: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 21:51:48,730: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-05 21:51:48,805: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2025-05-06 11:12:45,843: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-06 11:12:45,844: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 11:12:45,846: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 11:12:45,847: INFO: common: created directory at: artifacts]
[2025-05-06 11:12:45,847: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-06 11:12:45,848: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 11:12:50,756: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 11:12:50,967: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-06 11:12:50,967: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-05-06 11:12:50,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 11:12:50,969: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 11:12:50,970: INFO: common: created directory at: artifacts]
[2025-05-06 11:12:50,970: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-06 11:12:51,350: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 11:12:51,454: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 11:12:51,524: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2025-05-06 11:54:10,705: WARNING: module_wrapper: From c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\components\model_trainer.py:7: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-05-06 11:54:10,706: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-06 11:54:10,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 11:54:10,708: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 11:54:10,709: INFO: common: created directory at: artifacts]
[2025-05-06 11:54:10,709: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-06 11:54:10,710: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 11:54:18,059: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 11:54:18,293: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-06 11:54:18,293: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-05-06 11:54:18,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 11:54:18,296: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 11:54:18,297: INFO: common: created directory at: artifacts]
[2025-05-06 11:54:18,297: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-06 11:54:18,608: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 11:54:18,742: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 11:54:18,852: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2025-05-06 11:54:18,853: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-06 11:54:18,854: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 11:54:18,855: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 11:54:18,856: INFO: common: created directory at: artifacts]
[2025-05-06 11:54:18,856: INFO: common: created directory at: artifacts\training]
[2025-05-06 11:54:35,787: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 11:54:35,912: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 16:37:31,531: WARNING: module_wrapper: From c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\components\model_trainer.py:7: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-05-06 16:37:33,076: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-06 16:37:33,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 16:37:33,080: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 16:37:33,082: INFO: common: created directory at: artifacts]
[2025-05-06 16:37:33,082: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-06 16:37:33,083: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 16:37:41,191: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 16:37:41,487: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-06 16:37:41,487: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-05-06 16:37:41,488: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 16:37:41,489: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 16:37:41,490: INFO: common: created directory at: artifacts]
[2025-05-06 16:37:41,490: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-06 16:37:41,917: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 16:37:42,305: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 16:37:42,470: INFO: main: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2025-05-06 16:37:42,471: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-05-06 16:37:42,474: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 16:37:42,476: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 16:37:42,477: INFO: common: created directory at: artifacts]
[2025-05-06 16:37:42,478: INFO: common: created directory at: artifacts\training]
[2025-05-06 16:38:07,579: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 16:38:07,715: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 16:38:07,715: INFO: main: >>>>>> stage Evaluation started <<<<<<]
[2025-05-06 16:38:07,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 16:38:07,720: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 16:38:07,720: INFO: common: created directory at: artifacts]
[2025-05-06 16:38:07,929: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 16:38:16,649: INFO: common: json file saved at: scores.json]
[2025-05-06 16:38:52,108: INFO: main: >>>>>> stage Evaluation completed <<<<<<

x==========x]
[2025-05-06 17:19:19,919: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-06 17:19:19,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:19:19,922: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:19:19,922: INFO: common: created directory at: artifacts]
[2025-05-06 17:19:19,924: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-06 17:19:19,925: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 17:19:26,173: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 17:19:26,446: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-06 17:19:58,240: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2025-05-06 17:19:58,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:19:58,244: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:19:58,244: INFO: common: created directory at: artifacts]
[2025-05-06 17:19:58,245: INFO: common: created directory at: artifacts/data_ingestion]
[2025-05-06 17:19:58,245: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 17:20:03,232: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Tzusrrt9iAf0MgjTZSzgbcutEfhENsXA/view?usp=sharing to artifacts/data_ingestion/data.zip]
[2025-05-06 17:20:03,436: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-05-06 17:20:09,904: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-05-06 17:20:09,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:20:09,908: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:20:09,909: INFO: common: created directory at: artifacts]
[2025-05-06 17:20:09,909: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-05-06 17:20:10,230: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:20:10,356: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:20:10,442: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2025-05-06 17:21:13,986: WARNING: module_wrapper: From c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\components\model_trainer.py:7: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.
]
[2025-05-06 17:21:13,997: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2025-05-06 17:21:13,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:21:14,001: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:21:14,001: INFO: common: created directory at: artifacts]
[2025-05-06 17:21:14,002: INFO: common: created directory at: artifacts\training]
[2025-05-06 17:21:29,298: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-05-06 17:21:29,385: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-05-06 17:21:36,855: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation started <<<<<<]
[2025-05-06 17:21:36,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-05-06 17:21:36,860: INFO: common: yaml file: params.yaml loaded successfully]
[2025-05-06 17:21:36,860: INFO: common: created directory at: artifacts]
[2025-05-06 17:21:37,054: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 17:21:42,134: INFO: common: json file saved at: scores.json]
[2025-05-06 17:22:11,654: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation completed <<<<<<

x==========x]
[2025-05-06 18:04:57,482: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.226:8080]
[2025-05-06 18:04:57,482: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-06 18:05:05,000: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:05:05] "GET / HTTP/1.1" 200 -]
[2025-05-06 18:05:24,634: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\aldoe\Documents\Projects_Python\CT-SCAN\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-05-06 18:05:24,641: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:05:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-06 18:06:24,213: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:06:24] "GET / HTTP/1.1" 200 -]
[2025-05-06 18:06:27,974: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\flask_cors\decorator.py", line 121, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\aldoe\Documents\Projects_Python\CT-SCAN\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\aldoe\documents\projects_python\ct-scan\src\cnnClassifier\pipeline\prediction.py", line 18, in predict
    # model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\keras\src\saving\saving_api.py", line 196, in load_model
    return legacy_h5_format.load_model_from_hdf5(
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\aldoe\anaconda3\envs\myenv\lib\site-packages\h5py\_hl\files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2025-05-06 18:06:27,978: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:06:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-05-06 18:06:40,807: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.226:8080]
[2025-05-06 18:06:40,808: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-06 18:06:42,047: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:06:42] "GET / HTTP/1.1" 200 -]
[2025-05-06 18:06:45,726: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 18:06:46,174: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:06:46] "POST /predict HTTP/1.1" 200 -]
[2025-05-06 18:06:54,148: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 18:06:54,395: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:06:54] "POST /predict HTTP/1.1" 200 -]
[2025-05-06 18:07:32,772: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 18:07:33,019: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:07:33] "POST /predict HTTP/1.1" 200 -]
[2025-05-06 18:07:34,235: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 18:07:34,486: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:07:34] "POST /predict HTTP/1.1" 200 -]
[2025-05-06 18:07:35,149: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 18:07:35,370: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001DC15C5B7F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-05-06 18:07:35,395: INFO: _internal: 127.0.0.1 - - [06/May/2025 18:07:35] "POST /predict HTTP/1.1" 200 -]
[2025-05-06 21:07:13,716: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.226:8080]
[2025-05-06 21:07:13,716: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-05-06 21:07:25,798: INFO: _internal: 127.0.0.1 - - [06/May/2025 21:07:25] "GET / HTTP/1.1" 200 -]
[2025-05-06 21:07:29,578: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-05-06 21:07:30,290: INFO: _internal: 127.0.0.1 - - [06/May/2025 21:07:30] "POST /predict HTTP/1.1" 200 -]
